### ISSUE TITLE
Resolve TODO issues

### ISSUE THREAD

**Issue by Pomax** [Pomax/mj#163]
- [ ] game.js should not be effecting UI changes through the wind rotation
- [ ] cover earthly hand by robbing a kong on the initial deal
- [ ] bot.checkKong() run a kong declaration by the bot's personality
