### ISSUE TITLE
Take a break and do some documentation/refactoring/structuring of code

### ISSUE THREAD

**Issue by Pomax** [Pomax/mj#61]
This needs to still be maintainable 3 months from now, and some classes are getting quite large. It's a good idea to take a development break and switch to some maintenance soon, after:

- [x] #54 concealed kong flags
- [x] #57 ensure all tiles are visible to player
- [x] #59 add 'ready' button for human players

**Comment by Pomax** [comment]
MARKED OBSOLETE WITH CLIENT/SERVER IMPLEMENTATION
